config/routes.rb
Rails.application.routes.draw do
  captcha_route
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope "(:locale)", :locale => /en|fr/ do
    resources :user, only: [:index, :edit, :update]
    devise_for :user
    root 'user#index'
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :secure_validatable

  validates_uniqueness_of :login, :email, case_sensitive: false
  validates_presence_of :login, :email
  validates_length_of :password, minimum: 8

  def to_s
    "#{self.login} - #{self.email}"
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(login) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :secure_validatable, :security_questionable

  validates_uniqueness_of :login, :email, case_sensitive: false
  validates_presence_of :login, :email
  validates_length_of :password, minimum: 8
  validates_format_of :password, with: /(?=.*\d)(?=.*[a-z])(?=.*[A-Z])/
  attr_accessor :captcha

  def to_s
    "#{self.login} - #{self.email}"    
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(login) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # reset captcha code after each request for security
  after_filter :reset_last_captcha_code!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:email, :captcha)
    devise_parameter_sanitizer.for(:sign_in).push(:email)
    devise_parameter_sanitizer.for(:account_update).push(:login, :email)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    if !user_signed_in?
      flash[:notice] = "Nope, Sign in first"
      redirect_to new_user_session_path and return
    end
  end

  def edit
    if !user_signed_in?
      flash[:notice] = "Nope, Sign in first"
      redirect_to new_user_session_path and return
    end
    @user = User.find(params[:id])
    if @user.nil?
      flash[:notice] = "No user found"
      redirect_to root_path and return
    end
  end

  def update
    if !user_signed_in?
      flash[:notice] = "Nope, Sign in first"
      redirect_to new_user_session_path and return
    end
    @user = User.find(params[:id])
    if update_user_params[:password].empty?
      params.require(:user).delete(:password)
      params.require(:user).delete(:password_confirmation)
      @user.assign_attributes update_user_params
      @user.valid?
      if !@user.errors.any? {|m| m == :email} && !@user.errors.any? {|m| m == :login}
        @user.save(validate: false)
        @user.errors.clear
        flash[:notice] = "Login/Email successfully changed !"
        render action: 'edit'
      else
        flash[:error] = "Could not save changes, please make sure the information entered is correct"
        render action: 'edit'
      end
    else
      if update_user_params[:password] == update_user_params[:password_confirmation]
        @user.assign_attributes update_user_params
        if @user.save
          flash[:alert] = "User successfully changed !"
          redirect_to root_path and return
        else
          if @user.errors.any? {|m| m == :password}
            @errors = []
            @user.errors.each do |err, msg|
              if err == :password
                @errors << {:password_confirmation => msg}
              end
            end
            @errors.each do |err|
              @user.errors.add(err.first[0].to_sym, err.first[1])
            end
          end
          flash[:error] = "Could not save changes, please make sure the information entered is correct"
          render action: 'edit'
        end
      else
        @user.errors.add(:password, "Passwords do not match")
        @user.errors.add(:password_confirmation, "Passwords do not match")
        flash[:error] = "Could not save changes, passwords do not match"
        render action: 'edit'
      end
    end
  end

  protected

  def update_user_params
    params.require(:user).permit(:login, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def field_class(resource, field_name)
    if resource.errors[:messages].any? {|m| m == field_name}
      return "has-error".html_safe
    else
      return "".html_safe
    end
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/_navbar.html.haml
.navbar.navbar-default.navbar-static-top{:role => "navigation"}
  .container
    .navbar-header
      = link_to image_tag("logo42.gif"), root_path, class:"navbar-brand"
    .navbar-collapse.collapse
      %ul.nav.navbar-nav
        - if user_signed_in?
          /
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            .btn.btn-block.btn-success.col-xs-6.col-sm-3.col-md-2
              = link_to(I18n.t('edit_account'), edit_user_path(id: current_user.id))
          %li
            .btn.btn-block.btn-danger
              = link_to I18n.t('.active_admin')[:devise][:links][:sign_out], destroy_user_session_path, :method => :delete
        - else
          %li
            .btn.btn-block.btn-success.col-xs-6.col-sm-3.col-md-2
              = link_to I18n.t('.active_admin')[:devise][:links][:sign_in], new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Framework1
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield :head
  %body
    = render "layouts/navbar"
    - flash.each do |name, msg|
      - if name == "notice"
        .alert.alert-success.alert-dismissible.fade.in{:role => "alert"}
          %button.close{"data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} &times;
            %span.sr-only Close
          = msg
      - elsif name == "alert"
        .alert.alert-warning.alert-dismissible.fade.in{:role => "alert"}
          %button.close{"data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} &times;
            %span.sr-only Close
          = msg
      - else
        .alert.alert-danger.alert-dismissible.fade.in{:role => "alert"}
          %button.close{"data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} &times;
            %span.sr-only Close
          = msg
    = yield
  %footer
    = link_to I18n.t('.contact_us')[:contacts][:new][:contact_us], contact_us_path

app/views/user/edit.html.haml
- content_for :head do
  = stylesheet_link_tag 'Devise/sign_up'

%h2= t('.title', :resource => :user , :default => "Edit #{(:user).to_s.humanize}")
= form_for(@user, :url => user_path(id: @user.id), html: {class: "form-horizontal"}) do |f|
  .form-inputs
    .row.tabs
      %ul.nav.nav-tabs.col-md-8.col-md-offset-2
        %li.active
          %a{"data-toggle" => "tab", :href => "#details"} Details
        %li
          %a{"data-toggle" => "tab", :href => "#password"} Mot de passe
    .tab-content
      #details.tab-pane.active
        .form-group
          = f.label :login, class: "col-sm-3 col-md-4 control-label #{field_class(@user, :login)}"
          .col-sm-6.col-md-4
            = f.text_field :login, autofocus: true, required: true, class: "form-control"
        .form-group
          = f.label :email, class: "col-sm-3 col-md-4 control-label #{field_class(@user, :email)}"
          .col-sm-6.col-md-4
            = f.email_field :email, required: true, class: "form-control"
      #password.tab-pane
        .form-group
          = f.label :password, class: "col-sm-3 col-md-4 control-label #{field_class(@user, :password)}"
          .col-sm-6.col-md-4
            = f.password_field :password, :hint => "laisser vide pour ne pas changer le mot de passe", :required => false, autocomplete: "off", class: "form-control"
        .form-group
          = f.label :password_confirmation, class: "col-sm-3 col-md-4 control-label #{field_class(@user, :password)}"
          .col-sm-6.col-md-4
            = f.password_field :password_confirmation, :required => false, class: "form-control"
    .form-group
      .col-xs-6.col-xs-offset-3.col-sm-4.col-sm-offset-4.col-md-2.col-md-offset-5.submit
        = f.submit I18n.t('update'), class: "btn btn-block btn-success"
    .form-group
      .col-xs-6.col-xs-offset-3.col-sm-4.col-sm-offset-4.col-md-2.col-md-offset-5.submit
        = link_to t('devise.shared.links.back', :default => "Back"), :back
        %p
          = t('.unhappy', :default => 'Unhappy')
          ? #{link_to t('.cancel_my_account', :default => "Cancel my account"), registration_path(:user), :data => { :confirm => t('.are_you_sure', :default => "Are you sure?") }, :method => :delete}.